---
title: "Data Validation Plan"
format:
  revealjs: 
    theme: [simple, custom.scss]
    embed-resources: true
editor: visual
---

## Data Validation Process {.smaller}

### Quantitative Data Validation {.smaller}

-   **GPP data: Country data validation and outcomes validaton**

-   QRQ data validation

### Qualitative Checks

-   Traditional qualitative cross-checks

-   **Massive analysis using AI**

-   Interviews with experts

# GPP Quantitative Validation

## Quantitative Validation {.smaller}

- Country data validation: Pretest

- Country data validation: Full fieldwork

- Outcomes Validation

## Country data validation  {.smaller}

::: {.panel-tabset}

## Sample Representativeness

- Sample distributions

    - By sociodemographic group
    - By NUTS and country level


- Missing values
- Difficulty score (Face-to-Face only)
    
## Patterns and Correspondence

- Internal checks (key variables)
    - Overtime changes (t-test)
    - Subnational rankings*
- External checks (Multilevel analysis)
    - Aggregated scores analysis (level 1)
    - Question level analysis (level 2)
    - Extreme outlier detection (level 3)
    
:::
## Country data validation: Pretest {.smaller}

- INSERTAR FLOW CHART

- Deliverable: A report document along with a supplementary Excel file for each country. 

## Country data validation: Full fieldwork {.smaller}

- INSERTAR FLOW CHART

- Deliverable: Internal report or platform summarizing flags and issues at the country level. 

## Deliverables Desing 

- HTML country report that contains a list of flags by pillar. 

    - Attach to the HTML 

## Outcomes Validation {.smaller}

- INSERTAR FLOW CHART

- Deliverable: A new tab will be introduced within the internal report platform. This tab will highlight data points that could be considered controversial. 

# Task and Current Status {.smaller}

## Tasks {.smaller}

::: {.panel-tabset}

## Variables Selection

**Responsible:** Horacio and Gustavo \
**Support:** Data Analytics

- TPS selection (90%)
- Internal data selection (80%)
- TPS recollection, data and cleaning (90%)

## Functions to Validation

**Responsible:** Data Analytics \
**Support:** Natalia Rodriguez

- Country data validation: methodology functions creation (30%)
- Outcomes validation: methodology functions creation (0%)

## Deliverables design

**Responsible:** Data Analytics

- Design of reports and excels for Pretest (30%)
- Platform design and creation (0%)

:::

## Next steps {.smaller}

- QRQ data validation
- Pretest data validation
- Full fieldwork data validation
- Outcomes validation

# Massive analysis using AI overview

## Developing a news articles gathering and classification system {.smaller}

- Data collection trough a news data API

    - Access to a massive news data archive (1.000.000 articles per month)
    - Filter data by topic, newspaper and date

- Data labeling

    - WebApp to help team labeling data
    
- Model training

    - Machine Learning and Neural Networks (drip modelling)
    - AWS cloud computing (depends of the model)
    
- Model deployment (TBD)

## Implementing extensions (analysis) {.smaller}


- Topic Modeling Analysis

    - Identify number of topics, along with keywords and events for each one of them
    
- Summary of events

    - Automatic summaries of clustered news data
    
- Country/regional report
    
    - Summary of main news articles and events highligting key topic.
  


